### ISSUE TITLE
Setup script doesn't work with Python 3.7

### ISSUE THREAD

**Issue by Bscout2011** [MicrosoftDocs/sql-docs#1391]
The setup script says it's built to run on python 2, but my default python is python 3. How do I change this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5634d572-0020-808b-693a-13addc8861d9
* Version Independent ID: 136bab7d-d4d1-1e82-ba89-be2020bc784b
* Content: [Get started with SQL Server on Ubuntu](https://docs.microsoft.com/en-us/sql/linux/quickstart-install-connect-ubuntu?view=sql-server-2017)
* Content Source: [docs/linux/quickstart-install-connect-ubuntu.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/quickstart-install-connect-ubuntu.md)
* Product: **sql**
* GitHub Login: @rothja
* Microsoft Alias: **jroth**

**Comment by Bscout2011** [comment]
make a symlink for my python bin path as described here: https://askubuntu.com/questions/637848/how-to-reset-python-path-to-usr-bin-python

**Comment by rothja** [comment]
@Bscout2011 Hi. I'm sorry, but I'm not sure I see what script you're referring to? Thanks!

**Comment by rothja** [comment]
@Bscout2011 Do you still need some help on this issue? If so, can you let me know some more details about your scenario? Thanks!

**Comment by kosist** [comment]
I've got the same issue - how could I solve it? Thanks in advance!

**Comment by rothja** [comment]
@kosist, could you give me the exact error you're seeing? Is this when you run mssql-conf setup? Thanks!

**Comment by kosist** [comment]
> @kosist, could you give me the exact error you're seeing? Is this when you run mssql-conf setup? Thanks!

@rothja , thank you for your reply! Below is the trace:
```
~$ sudo apt-get install -y mssql-server
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  libactivation-java libapache-pom-java libatinject-jsr330-api-java
  libbcmail-java libbcpkix-java libbcprov-java libcommons-io-java
  libcommons-lang3-java libcommons-parent-java libfontawesomefx-java
  libfontbox2-java libgeronimo-validation-1.0-spec-java
  libgettext-commons-java libgraphicsmagick++-q16-12 libgraphicsmagick-q16-3
  libhibernate-validator-java libimgscalr-java libjackson2-core-java
  libjackson2-jr-java libjboss-logging-java liblogback-java libmail-java
  libmetadata-extractor-java libopenjfx-java libopenjfx-jni libpython-all-dev
  libpython-dev libpython2.7-dev librsync1 libsambox-java libsdl-ttf2.0-0
  libsdl1.2debian libsejda-eventstudio-java libsejda-injector-java
  libsejda-io-java libsejda-java libslf4j-java libtwelvemonkeys-java
  libxmpcore-java openjfx qtdeclarative5-qtquick2-plugin
Use 'sudo apt autoremove' to remove them.
The following NEW packages will be installed:
  mssql-server
0 upgraded, 1 newly installed, 0 to remove and 76 not upgraded.
Need to get 0 B/176 MB of archives.
After this operation, 931 MB of additional disk space will be used.
Preconfiguring packages ...
Selecting previously unselected package mssql-server.
(Reading database ... 205131 files and directories currently installed.)
Preparing to unpack .../mssql-server_14.0.3048.4-1_amd64.deb ...
Unpacking mssql-server (14.0.3048.4-1) ...
Processing triggers for libc-bin (2.27-3ubuntu1) ...
Setting up mssql-server (14.0.3048.4-1) ...
Traceback (most recent call last):
  File "/opt/mssql/bin/../lib/mssql-conf/mssql-conf.py", line 15, in <module>
    import mssqlconfhelper
  File "/opt/mssql/lib/mssql-conf/mssqlconfhelper.py", line 155
    print _("Setting language using LCID from environment variable %s") % mssqlLcidEnvVariable
          ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "/opt/mssql/bin/../lib/mssql-conf/mssql-conf.py", line 15, in <module>
    import mssqlconfhelper
  File "/opt/mssql/lib/mssql-conf/mssqlconfhelper.py", line 155
    print _("Setting language using LCID from environment variable %s") % mssqlLcidEnvVariable
          ^
SyntaxError: invalid syntax
Processing triggers for man-db (2.8.3-2ubuntu0.1) ...
Processing triggers for libc-bin (2.27-3ubuntu1) ...
```
