### ISSUE TITLE
Database Diagrams Deprecated

### ISSUE THREAD

**Issue by cOborski** [MicrosoftDocs/sql-docs#2237]
According to the release notes [https://docs.microsoft.com/en-us/sql/ssms/release-notes-ssms?view=sql-server-2017#180-ga-april-2019] database diagrams have been depreciated. Why don't you put a warning at the top of this page explaining that this feature will not be available for versions including and after 15.0.18118.0?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a34a1f6-ca51-920d-eddc-e8a9d0395380
* Version Independent ID: 17fb383b-83e6-0959-2b47-bb50cec87290
* Content: [Walkthrough: Adding and Changing a Database Diagram - SQL Server](https://docs.microsoft.com/en-us/sql/ssms/visual-db-tools/walkthrough-adding-and-changing-a-database-diagram?view=sql-server-2017)
* Content Source: [docs/ssms/visual-db-tools/walkthrough-adding-and-changing-a-database-diagram.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/ssms/visual-db-tools/walkthrough-adding-and-changing-a-database-diagram.md)
* Product: **sql**
* Technology: **ssms**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by MightyPen** [comment]
@markingmyname Hi Mark, Can you please process this Issue 2237.  Thanks.

**Comment by markingmyname** [comment]
Hi @cOborski,

Due to feedback, we have decided to return this feature to SSMS.  The plan is to return this feature in release 18.1.

Hope this helps.

Thank you.

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue.

**Comment by dunderburken** [comment]
Hi @markingmyname,

Opening newly created Database Diagrams does not work in SSMS 18.3.1 & 18.4 (have tried earlier versions too)

Error message:

===================================

Attempted to read or write protected memory. This is often an indication that other memory is corrupt. (Microsoft.VisualStudio.OLE.Interop)

------------------------------
Program Location:

at Microsoft.VisualStudio.OLE.Interop.IOleCommandTarget.Exec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
at Microsoft.VisualStudio.Platform.WindowManagement.DocumentObjectSite.Exec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
at Microsoft.VisualStudio.Platform.WindowManagement.WindowFrame.Exec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
at Microsoft.Internal.VisualStudio.Shell.Interop.IVsTrackSelectionExPrivate.Register()
at Microsoft.VisualStudio.Platform.WindowManagement.WindowFrame.ConnectSelectionContext()
at Microsoft.VisualStudio.Platform.WindowManagement.WindowFrame.Activate()
at Microsoft.VisualStudio.Platform.WindowManagement.WindowManagerService.viewManager_ActiveViewChanged(Object sender, ActiveViewChangedEventArgs e)
at Microsoft.VisualStudio.PlatformUI.ExtensionMethods.RaiseEvent[TEventArgs](EventHandler`1 eventHandler, Object source, TEventArgs args)
at Microsoft.VisualStudio.PlatformUI.Shell.ViewManager.SetActiveView(View view, ActivationType type)
at Microsoft.VisualStudio.Platform.WindowManagement.WindowFrame.ShowInternal(ShowFlags showFlags)
at Microsoft.VisualStudio.Platform.WindowManagement.WindowFrame.<Show>b__483_0()
at Microsoft.VisualStudio.ErrorHandler.CallWithCOMConvention(Func`1 method, Boolean reportError, Boolean setShellErrorInfo)
at Microsoft.VisualStudio.Platform.WindowManagement.WindowFrame.Show()
at Microsoft.VisualStudio.Platform.WindowManagement.WindowFrame.MarshalingWindowFrame.<Microsoft.VisualStudio.Shell.Interop.IVsWindowFrame.Show>b__12_0()
at Microsoft.VisualStudio.Shell.ThreadHelper.Invoke[TResult](Func`1 method)
at Microsoft.VisualStudio.Platform.WindowManagement.WindowFrame.MarshalingWindowFrame.Microsoft.VisualStudio.Shell.Interop.IVsWindowFrame.Show()
at Microsoft.SqlServer.Management.UI.VSIntegration.Editors.VirtualProject.CreateDesigner(Urn origUrn, DocumentType editorType, DocumentOptions aeOptions, IManagedConnection con, String fileName)
at Microsoft.SqlServer.Management.UI.VSIntegration.Editors.VirtualProject.Microsoft.SqlServer.Management.UI.VSIntegration.Editors.ISqlVirtualProject.CreateDesigner(Urn origUrn, DocumentType editorType, DocumentOptions aeOptions, IManagedConnection con, String fileName)
at Microsoft.SqlServer.Management.UI.VSIntegration.Editors.ISqlVirtualProject.CreateDesigner(Urn origUrn, DocumentType editorType, DocumentOptions aeOptions, IManagedConnection con, String fileName)
at Microsoft.SqlServer.Management.UI.VSIntegration.Editors.VsDocumentMenuItem.CreateDesignerWindow(IManagedConnection mc, DocumentOptions options)
at Microsoft.SqlServer.Management.UI.VSIntegration.Editors.VsDocumentMenuItem.InvokeDesigner(IManagedConnection connection)
at Microsoft.SqlServer.Management.UI.VSIntegration.Editors.VsDocumentMenuItem.Invoke()
at Microsoft.SqlServer.Management.UI.VSIntegration.ObjectExplorer.ToolsMenuItemBase.MenuInvokedHandler(Object sender, EventArgs args)

Please see: https://feedback.azure.com/forums/908035-sql-server/suggestions/37992649-ssms-18-1-crashes-when-opening-a-database-diagram
