### ISSUE TITLE
azdata bdc create error

### ISSUE THREAD

**Issue by mwdarab** [MicrosoftDocs/sql-docs#3902]
I was redirected here after creating the 3 node kubeadm cluster. I successfully installed azdata, etc. but when I run "azdata bdc create" I get the below error:

mwdarab@bdc-master:~$ azdata bdc create
libodbc.so.2: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/opt/azdata/lib/python3.6/site-packages/mssqlctl/cli/core/__init__.py", line 191, in invoke
    args=args)
  File "/opt/azdata/lib/python3.6/site-packages/knack/cli.py", line 162, in raise_event
    func(self, **kwargs)
  File "/opt/azdata/lib/python3.6/site-packages/mssqlctl/cli/core/logging.py", line 139, in init_command_file_logging      self._init_command_logfile_handlers(cmd_logger, args)
  File "/opt/azdata/lib/python3.6/site-packages/mssqlctl/cli/core/logging.py", line 150, in _init_command_logfile_handlers
    self.cli_ctx.invocation.commands_loader.load_command_table(args)
  File "/opt/azdata/lib/python3.6/site-packages/mssqlctl/cli/core/commands.py", line 60, in load_command_table
    merge.update(_load_module_command_loader(self, args, mod))
  File "/opt/azdata/lib/python3.6/site-packages/mssqlctl/cli/core/commands.py", line 24, in _load_module_command_loader    command_table = command_loader.load_command_table(args)
  File "/opt/azdata/lib/python3.6/site-packages/mssqlctl/cli/commands/sql/__init__.py", line 17, in load_command_table     from mssqlctl.cli.commands.sql.command_table import load_command_table
  File "/opt/azdata/lib/python3.6/site-packages/mssqlctl/cli/commands/sql/command_table.py", line 6, in &lt;module&gt;           from mssqlctl.cli.commands.sql import client
  File "/opt/azdata/lib/python3.6/site-packages/mssqlctl/cli/commands/sql/client.py", line 16, in &lt;module&gt;
    import pyodbc
ImportError: libodbc.so.2: cannot open shared object file: No such file or directory

Is there something that I missed that (potentially was not in the documentation)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f789883-5a24-a045-21d5-4b95951cb798
* Version Independent ID: fadbef40-b033-7e4f-533a-abd7a8e303db
* Content: [Deployment guidance - SQL Server Big Data Clusters](https://docs.microsoft.com/en-us/sql/big-data-cluster/deployment-guidance?view=sql-server-ver15#deploy)
* Content Source: [docs/big-data-cluster/deployment-guidance.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/big-data-cluster/deployment-guidance.md)
* Product: **sql**
* Technology: **big-data-cluster**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@mwdarab -- Mohammad, thank you for your feedback.

@MikeRayMSFT -- Mike, please look into this issue 3902.

**Comment by mihaelablendea** [comment]
Please use one of the packaged installers to setup azdata. I.e. https://docs.microsoft.com/en-us/sql/big-data-cluster/deploy-install-azdata-linux-package?view=sql-server-ver15

If you use pip, you would need to manually install dependencies. I.e. https://docs.microsoft.com/en-us/sql/big-data-cluster/deploy-install-azdata-pip?view=sql-server-ver15#linux
