### ISSUE TITLE
Can not edit SSIS step in SQL Aget Job SSMS 18.5

### ISSUE THREAD

**Issue by alexanderlazutkin** [MicrosoftDocs/sql-docs#4526]
Can not edit SSIS step in SQL Aget Job . Previous version worked without this error: 

===================================

Specified cast is not valid. (Microsoft.DatatransformationServices.DTSExecUI.Controls)

------------------------------
Program Location:

   at Microsoft.DataTransformationServices.DTSExecUI.Controls.BaseControl.GetCredential(MgdParser parser, CredentialType credentialType)
   at Microsoft.DataTransformationServices.DTSExecUI.Controls.ExecutionOptionsCtrl.InitWithParser(MgdParser parser)
   at Microsoft.DataTransformationServices.DTSExecUI.Controls.BaseControl.InitViewWithParser(MgdParser parser)
   at Microsoft.SqlServer.Management.SqlManagerUI.DTSJobSubSystemDefinition.Microsoft.SqlServer.Management.SqlManagerUI.IJobStepPropertiesControl.Load(JobStepData data)
   at Microsoft.SqlServer.Management.SqlManagerUI.JobStepProperties.UpdateJobStep()
   at Microsoft.SqlServer.Management.SqlManagerUI.JobStepProperties.typeList_SelectedIndexChanged(Object sender, EventArgs e)
   at System.Windows.Forms.ComboBox.OnSelectedIndexChanged(EventArgs e)
   at System.Windows.Forms.ComboBox.set_SelectedIndex(Int32 value)
   at System.Windows.Forms.ComboBox.set_SelectedItem(Object value)
   at Microsoft.SqlServer.Management.SqlManagerUI.JobStepProperties.InitializeStepCombo()
   at Microsoft.SqlServer.Management.SqlManagerUI.JobStepProperties.InitializeData()
   at Microsoft.SqlServer.Management.SqlManagerUI.JobStepProperties.OnInitialization()
   at Microsoft.SqlServer.Management.SqlMgmt.ViewSwitcherControlsManager.SetView(Int32 index, TreeNode node)
   at Microsoft.SqlServer.Management.SqlMgmt.ViewSwitcherControlsManager.SelectCurrentNode()
   at Microsoft.SqlServer.Management.SqlMgmt.ViewSwitcherControlsManager.InitializeUI(ViewSwitcherTreeView treeView, ISqlControlCollection viewsHolder, Panel rightPane)
   at Microsoft.SqlServer.Management.SqlMgmt.LaunchForm.InitializeForm(XmlDocument doc, IServiceProvider provider, ISqlControlCollection control)
   at Microsoft.SqlServer.Management.SqlMgmt.LaunchForm..ctor(ISqlControlCollection control, IServiceProvider provider)
   at Microsoft.SqlServer.Management.SqlManagerUI.JobSteps.OnDoubleClick(Object sender, MouseButtonDoubleClickedEventArgs args)
   at Microsoft.SqlServer.Management.UI.Grid.GridControl.OnMouseButtonDoubleClicked(HitTestResult htArea, Int64 nRowIndex, Int32 nColIndex, Rectangle rCellRect, MouseButtons btn, GridButtonArea headerArea)
   at Microsoft.SqlServer.Management.SqlManagerUI.SqlManagerUIDlgGrid.OnMouseButtonDoubleClicked(HitTestResult htArea, Int64 rowIndex, Int32 colIndex, Rectangle cellRect, MouseButtons btn, GridButtonArea headerArea)
   at Microsoft.SqlServer.Management.UI.Grid.GridControl.OnMouseDown(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseDown(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at Microsoft.SqlServer.Management.UI.Grid.GridControl.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.RunDialog(Form form)
   at System.Windows.Forms.Form.ShowDialog(IWin32Window owner)
   at System.Windows.Forms.Form.ShowDialog()
   at Microsoft.SqlServer.Management.SqlMgmt.RunningFormsTable.RunningFormsTableImpl.ThreadStarter.StartThread()

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45daf2f0-bb22-338f-062b-a9fabcb71a92
* Version Independent ID: b6e909fe-15d9-c1cf-c018-d4f6f36ff31f
* Content: [Download SQL Server Management Studio (SSMS) - SQL Server Management Studio (SSMS)](https://docs.microsoft.com/en-us/sql/ssms/download-sql-server-management-studio-ssms?view=sql-server-ver15)
* Content Source: [docs/ssms/download-sql-server-management-studio-ssms.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/ssms/download-sql-server-management-studio-ssms.md)
* Product: **sql**
* Technology: **ssms**
* GitHub Login: @dnethi
* Microsoft Alias: **dinethi**

**Comment by WilliamAntonRohm** [comment]
@alexanderlazutkin -- thank you for your feedback.  I am looking into this issue.

**Comment by markingmyname** [comment]
@alexanderlazutkin 

Thanks for bringing this to our attention.

We are currently investigating this issue.

Thank you.

**Comment by Matteo-T** [comment]
@alexanderlazutkin - I was not able to repro the issue so far, so perhaps it may be specific to the form/shape of your SSIS step. 

- Any chance you can share a bit of details about it? Maybe screenshots, the package you are using, etc..

- Another relevant question is: are you connected to an "on-prem" SQL Server instance (if so, what version? SQL 2019?) or an Azure SQL MI?

- Could youshare the command line for his sql agent job step? You can get the command line using "select * from dbo.sysjobsteps" and filtering on the step you are having issues with

- Can you confirm you used SSMS 18.4 (or earlier) to create the job and you are having issues editing it with 185.5?

**Comment by alexanderlazutkin** [comment]
1. I uninstalled 18.5 version and installed 18.4 on my notebook. Possible if I install 18.5 version again  I reproduce it and answer p. 1 and 3. But later next answers
2. I work with Azure SQL MI
4. Yes. I had created jobs in 18.4 and tried change them in 18.5

**Comment by Matteo-T** [comment]
Thanks. I've passed the info to the SSIS folks and they think they identified the problem. Thanks so much for reporting it.

**Comment by markingmyname** [comment]
@alexanderlazutkin

We acknowledge this is an issue.

As such, we will address this issue in a later release.

Thank you again for bringing this to our attention.

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue. To see what the community is wanting, please visit the [UserVoice](https://feedback.azure.com/forums/908035-sql-server) site.
