### ISSUE TITLE
Sample script for ActiveDirectoryServicePrincipal authentication mode doesn't work

### ISSUE THREAD

**Issue by venkis81** [MicrosoftDocs/sql-docs#6936]
Exception in thread "main" com.microsoft.sqlserver.jdbc.SQLServerException: Failed to authenticate the user XYZ in Active Directory (Authentication=ActiveDirectoryServicePrincipal). java.net.ConnectException: Connection refused: no further information
	at com.microsoft.sqlserver.jdbc.SQLServerMSAL4JUtils.getCorrectedException(SQLServerMSAL4JUtils.java:228)
	at com.microsoft.sqlserver.jdbc.SQLServerMSAL4JUtils.getSqlFedAuthTokenPrincipal(SQLServerMSAL4JUtils.java:91)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.getFedAuthToken(SQLServerConnection.java:4765)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.onFedAuthInfo(SQLServerConnection.java:4724)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.processFedAuthInfo(SQLServerConnection.java:4680)
	at com.microsoft.sqlserver.jdbc.TDSTokenHandler.onFedAuthInfo(tdsparser.java:289)
	at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:125)
	at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:37)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.sendLogon(SQLServerConnection.java:5560)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.logon(SQLServerConnection.java:4289)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.access$000(SQLServerConnection.java:88)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection$LogonCommand.doExecute(SQLServerConnection.java:4227)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7417)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:3488)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectHelper(SQLServerConnection.java:2978)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.login(SQLServerConnection.java:2628)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectInternal(SQLServerConnection.java:2471)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connect(SQLServerConnection.java:1470)
	at com.microsoft.sqlserver.jdbc.SQLServerDataSource.getConnectionInternal(SQLServerDataSource.java:1317)
	at com.microsoft.sqlserver.jdbc.SQLServerDataSource.getConnection(SQLServerDataSource.java:100)
	at AADServicePrincipal.main(AADServicePrincipal.java:19)
Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.net.ConnectException: Connection refused: no further information
	at com.microsoft.sqlserver.jdbc.SQLServerMSAL4JUtils.getCorrectedException(SQLServerMSAL4JUtils.java:226)
	... 20 more
Caused by: java.lang.RuntimeException: java.net.ConnectException: Connection refused: no further information
	at com.microsoft.sqlserver.jdbc.SQLServerMSAL4JUtils.getCorrectedException(SQLServerMSAL4JUtils.java:218)
	... 20 more

**Comment by venkis81** [comment]
These are libraries in my classpath

commons-lang3-3.0.jar
json-smart-1.0.6.3.jar
msal4j-1.11.0.jar
oauth2-oidc-sdk-9.18.jar
slf4j-api-2.0.0-alpha5.jar
mssql-jdbc-9.4.0.jre8.jar also tried with mssql-jdbc-9.4.0.jre16.jar

**Comment by WilliamAntonRohm** [comment]
@venkis81 -- thank you for clarifying.  I am looking into this issue.

**Comment by WilliamAntonRohm** [comment]
@David-Engel -- please help investigate.

**Comment by WilliamAntonRohm** [comment]
@venkis81 -- thank you for your followup.

@David-Engel -- please look into this issue.

**Comment by David-Engel** [comment]
@venkis81 The error you are getting is not due to a problem with the sample script. It is due to an environment configuration / connectivity problem. I'm guessing you probably need to allow HTTPS connections from your client to the Azure Active Directory authentication servers or you need to configure Java to use your proxy (if you are behind a proxy). However, troubleshooting your environment is not within the scope of this repo. You'll need to engage Azure support to troubleshoot your issue.

Regards,
David

#please-close
