### ISSUE TITLE
Key store providers cannot be set more than once

### ISSUE THREAD

**Issue by mariocastillo86** [MicrosoftDocs/sql-docs#8962]
Hi,

I followed this article [](https://learn.microsoft.com/en-us/sql/connect/jdbc/using-always-encrypted-with-the-jdbc-driver?view=sql-server-ver16) to start working with "Always Encrypted" in my project. I have anJava Spring Boot application but I still getting "Key store providers cannot be set more than once" error when I try to start my application. Am I missing something?

**Project information**

Java 11
Spring boot 2.4.5

**Pom.xml dependencies**

```
<dependency>
	<groupId>com.microsoft.sqlserver</groupId>
	<artifactId>mssql-jdbc</artifactId>
</dependency>
<dependency>
	<groupId>com.microsoft.azure</groupId>
	<artifactId>adal4j</artifactId>
	<version>1.6.5</version>
</dependency>
<dependency>
	<groupId>com.microsoft.rest</groupId>
	<artifactId>client-runtime</artifactId>
	<version>1.7.14</version>
</dependency>
<dependency>
	<groupId>com.azure.spring</groupId>
	<artifactId>azure-spring-boot-starter-keyvault-secrets</artifactId>
</dependency>
<dependency>
	<groupId>com.nimbusds</groupId>
	<artifactId>oauth2-oidc-sdk</artifactId>
	<version>7.5</version>
	<scope>runtime</scope>
</dependency>
<dependency>
	<groupId>com.microsoft.azure</groupId>
	<artifactId>azure</artifactId>
	<version>1.41.4</version>
</dependency>
``` 

**Error**

com.microsoft.sqlserver.jdbc.SQLServerException: Key store providers cannot be set more than once.

`17-05-2023 13:14:14.123  [pool-mailchimp connection adder] DEBUG  c.m.sqlserver.jdbc.Connection.registerColumnEncryptionKeyStoreProviders - ENTRY Registering Column Encryption Key Store Providers
17-05-2023 13:14:14.123  [pool-mailchimp connection adder] DEBUG  c.m.s.j.internals.SQLServerException.logException - *** SQLException: com.microsoft.sqlserver.jdbc.SQLServerException: Key store providers cannot be set more than once. Key store providers cannot be set more than once.
17-05-2023 13:14:14.123  [pool-mailchimp connection adder] DEBUG  c.m.sqlserver.jdbc.Connection.close - ENTRY
17-05-2023 13:14:14.124  [pool-mailchimp connection adder] DEBUG  c.m.sqlserver.jdbc.Connection.close - RETURN
17-05-2023 13:14:14.124  [pool-mailchimp connection adder] DEBUG  com.zaxxer.hikari.pool.HikariPool.createPoolEntry - pool-mailchimp - Cannot acquire connection from data source
com.microsoft.sqlserver.jdbc.SQLServerException: Key store providers cannot be set more than once.
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.registerColumnEncryptionKeyStoreProviders(SQLServerConnection.java:746)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.registerKeyStoreProviderOnConnection(SQLServerConnection.java:1377)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectInternal(SQLServerConnection.java:1623)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connect(SQLServerConnection.java:1276)
	at com.microsoft.sqlserver.jdbc.SQLServerDriver.connect(SQLServerDriver.java:861)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:358)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:477)
	at com.zaxxer.hikari.pool.HikariPool.access$100(HikariPool.java:71)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:725)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:711)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)`

**Comment by WilliamAntonRohm** [comment]
@mariocastillo86 -- Mario, thank you for your thorough investigation, and congratulations on a successful resolution.
